config/routes.rb
Rails.application.routes.draw do

   root 'home#index'
   post 'cars_at_yallah' => 'home#cars_at_yallah_motors_models'
   post 'car_versions_at_yallah' => 'home#cars_at_yallah_motors_versions'
   post 'export_csv_file' => 'home#export_csv'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def scrap_yallah_motors_models(site_url)
    cars_data = []
    mechanize = Mechanize.new
    cars_model_page = mechanize.get(site_url)
    model_name_with_links = cars_model_page.links_with(:class => "new-car-name")
    model_name_with_links.each do |car_model_link|
      cars_data << {:Type => "Car Model", :Title => car_model_link.to_s.strip, :link => "http://uae.yallamotor.com#{car_model_link.uri.to_s}"}
    end
    cars_data
  end

  def scrap_yallah_motors_versions(site_url, model_name)
    cars_data = []
    mechanize = Mechanize.new
    sub_page = mechanize.get(site_url)
    cars_data << {:Type => "Car Model", :Title => model_name, :Price => ""}
    car_versions = sub_page.css(".prices-and-specs .content-box .new-cars-results")
    car_versions.each do |car_version|
      cars_data << {:Type => "Car Version", :Title => car_version.css(".new-cars-results-text h4 a").text.strip, :Price => car_version.css(".new-cars-results-text h4 span").text.strip}
    end
    cars_data
  end

  def generate_csv(data_for_csv)
    csv_file = CSV.generate do |csv|
      csv << ["TYPE", "TITLE", "PRICE"]
      data_for_csv.each do |car_info|
        csv << [car_info[0], car_info[1], car_info[2]]
      end
    end
    csv_file
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #Home Page Action
  end

  def cars_at_yallah_motors_models
    site_url = car_models_params[:site_url]
    cars_data = scrap_yallah_motors_models(site_url)
    respond_to do |format|
      format.json { render json: cars_data }
      format.html { render :nothing => true, :status => 200}
    end
  end

  def cars_at_yallah_motors_versions
    site_url = car_versions_params[:site_url]
    model_name = car_versions_params[:model_name]
    cars_data = scrap_yallah_motors_versions(site_url, model_name)
    respond_to do |format|
      format.json { render json: cars_data }
      format.html { render :nothing => true, :status => 200}
    end
  end

  def export_csv
    data_for_csv = JSON.parse(csv_params[:car_data_to_csv])
    csv_file = generate_csv(data_for_csv)
    respond_to do |format|
      format.csv { send_data csv_file, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=CarsAtYallah.csv" }
    end
  end

  def car_models_params
    params.permit(:site_url, :model_name)
  end

  def car_versions_params
    params.permit(:site_url, :model_name)
  end

  def csv_params
    params.permit(:car_data_to_csv)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="loading hidden" style="display: none; position: fixed;">Loading...</div>
<div class="box">
  <section class="hero backgroud" style="background: none; border: none; box-shadow: none;">

    <div class="row container">
      <div class="large-9 small-12 medium-9 columns large-centered">
        <h1 style="color:#255255">Search Your Url!</h1>
        <div class="row fullWidth">

        </div>


        <div class="row">

          <div class="left column large-12 small-12 medium-12">
            <div class="row collapse">
              <div class="small-9 large-9 medium-9 columns">
                <input class="domainbox animated left large-11 bounceInDown search-box" type="text" spellcheck="false" placeholder="Enter the Domain Name" maxlength="65" value="" style="display: block;">

              </div>


              <div class="small-3 large-3 medium-3 columns">
                <button class="button postfix search " id="search">
                  <div class="searchicon"></div>
                </button>
              </div>


            </div>


          </div>

        </div>
      </div>
    </div>

  </section>

  <!-- Second Row  ---------->



  <div class="left column large-12 small-12 medium-12 domainresults ">
    <div class="row">
      <div class="column  large-12 margin-top hidden" id="dvData" >
         <!--<button id="export_csv" class="button right">Download CSV</button>-->
         <%= button_to 'Download CSV',export_csv_file_path(format: "csv") ,:method => :post,:form_class => "csv_form right"  %>
        <table class="large-12 result_table">
          <thead>

          <tr>
            <th class='middle-fit bolder'>TYPE </th>
            <th  class='middle-fit bolder'>TITLE </th>
            <th  class='middle-fit bolder'>PRICE </th>
          </tr>
          </thead>
          <tbody id="cars-details-container">
          </tbody>
        </table>
      </div>
    </div>
  </div>

    </div>
   </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarsAtYallah</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div data-alert class="alert-box">
  </div>
    <%= yield %>
  </body>
</html>